Repository MerAuctions/MerAuctions, pull requests merged in 2019-11, with the labels that each got.

#44 added interest list to user struct type
  models/models.go
Labels: backend, enhancement

#45 Change auction struct
  models/models.go
Labels: backend, enhancement

#47 Change bid struct
  models/models.go
Labels: backend, enhancement

#53 Redeployment done
  Makefile
  kubernetes/merauction.yml
Labels: deployment

#55 deployment configs for docker and kubernetes
  Makefile
  kubernetes/merauction.yml
Labels: deployment

#58 circleci config
  .circleci/config.yml
Labels: deployment, testing

#57 Updated readme
  README.md
Labels: documentation

#60 Upload image and generate public URL for it
  .gitignore
  Makefile
  server/handlers.go
  server/routes.go
Labels: backend, enhancement

#62 Basic edits to backend and configs of gke, gcp and Docker
  .circleci/config.yml
  .gitignore
  Makefile
  README.md
  data/data.go
  db/db.go
  models/models.go
  server/handlers.go
  server/routes.go
  server/seed-data/auctions.json
  server/seed-data/bids.json
  server/seed-data/users.json
  server/server_test.go
  templates/auction_list/card.tmpl
Labels: backend, deployment, documentation, enhancement, testing

#63 Reward point endpoint and logic created
  .gitignore
  data/data.go
  db/db.go
  models/models.go
  server/handlers.go
  server/routes.go
  server/seed-data/users.json
  server/server_test.go
Labels: backend

#66 configuration for gcp, gke, docker and circleci set
  Makefile
  kubernetes/merauction.yml
Labels: deployment, enhancement, testing

#67 testing the entire CD and CI pipeline
  Makefile
  kubernetes/merauction.yml
Labels: deployment, enhancement, testing

#68 changes to image name
  .circleci/config.yml
Labels: deployment, enhancement, testing

#69 [deployment test] made changes to the image name
  .circleci/config.yml
Labels: deployment, enhancement, testing

#74 Frontend create auction
  .gitignore
  media/images/test1.png
  models/models.go
  server/handlers.go
  server/routes.go
  server/seed-data/auctions.json
  templates/auction_list/card.tmpl
  templates/auction_list/index.tmpl
  templates/common/navbar.tmpl
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: backend, frontend

#80 changed date field in create auction
  media/images/Screen Shot 2019-11-07 at 7.59.31.png
  media/images/test3.png
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: enhancement, frontend

#70 Added test for rewards endpoint
  data/data.go
  db/db.go
  models/models.go
  server/handlers.go
  server/routes.go
  server/seed-data/auctions.json
  server/seed-data/bids.json
  server/seed-data/users.json
  server/server_test.go
Labels: backend, testing

#81 Get tags for images
  .gitignore
  Makefile
  api/api.go
  kubernetes/merauction.yml
  models/models.go
  server/handlers.go
  server/routes.go
Labels: backend

#82 Get descriptions for images
  api/api.go
  media/images/Screen Shot 2019-11-07 at 7.59.31.png
  server/handlers.go
  server/routes.go
Labels: backend

#87 Fixed mapping issue
  data/data.go
  db/db.go
  media/images/apple-ios-12-hands-on-review-notification-center-wide.jpg
  models/models.go
  server/handlers.go
  server/seed-data/bids.json
  server/server_test.go
  templates/create_auction/index.tmpl
Labels: backend

#92 get tags and description for the user uploaded image
  api/api.go
  go.mod
  go.sum
  media/images/apple-ios-12-hands-on-review-notification-center-wide.jpg
  media/images/apple-news-app-notifications-preferences-and-notifications-screenshots-iphones.png
  media/images/beach.jpeg
  media/images/test1.png
  media/images/test3.png
  server/handlers.go
  server/server.go
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: backend, deployment, frontend

#84 /user/:id/auctions endpoint to fetch all the auctions for that particular user
  data/data.go
  db/db.go
  server/handlers.go
  server/routes.go
  server/seed-data/seeddb.go
Labels: backend

#97 Frontend create auction
  templates/create_auction/index.tmpl
Labels: backend, frontend

#95 Add test for getDescriptionfromImage and getTagsfromImage
  server/server_test.go
Labels: backend, testing

#101 Fix user_id conflicts
  server/handlers.go
  server/routes.go
Labels: testing

#102 Auction details page
  templates/auction/details.tmpl
  templates/auction_list/index.tmpl
  templates/create_auction/index.tmpl
Labels: frontend

#98 test release
  .gitignore
  Makefile
  api/api.go
  data/data.go
  db/db.go
  go.mod
  go.sum
  kubernetes/merauction.yml
  media/images/test1.png
  models/models.go
  server/handlers.go
  server/routes.go
  server/seed-data/auctions.json
  server/seed-data/bids.json
  server/seed-data/seeddb.go
  server/seed-data/users.json
  server/server.go
  server/server_test.go
  templates/auction/details.tmpl
  templates/auction_list/card.tmpl
  templates/auction_list/index.tmpl
  templates/common/navbar.tmpl
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: deployment, testing

#103 resolved end time issue on the details page
  templates/auction/index.tmpl
  templates/create_auction/index.tmpl
Labels: frontend

#106 Navbar routing
  templates/common/navbar.tmpl
Labels: frontend

#109 fix big bugs and some fatal
  data/data.go
  db/db.go
  media/images/3.png
  server/handlers.go
Labels: backend

#111 error handling and resolved bug of showing bids in frontend
  templates/auction/index.tmpl
Labels: frontend

#120 Added createdby on auction page
  server/seed-data/auctions.json
  templates/auction/details.tmpl
  templates/auction/index.tmpl
Labels: frontend

#122 Remove quotes and \n from description
  Makefile
  kubernetes/merauction.yml
  templates/create_auction/index.tmpl
Labels: frontend

#123 Added createdby
  server/handlers.go
  templates/auction/index.tmpl
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: backend, frontend

#124 final release before rehearsals
  Makefile
  kubernetes/merauction.yml
  server/handlers.go
  templates/auction/index.tmpl
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: backend, frontend, testing

#129 Add search by tag endpoint
  data/data.go
  db/db.go
  server/handlers.go
  server/routes.go
  templates/common/navbar.tmpl
Labels: backend, frontend

#128 using a fixed size for cards on the dashboard
  media/images/3.png
  media/images/beach.jpeg
  media/images/fridge.jpg
  media/images/test1.jpeg
  media/images/test1.png
  server/seed-data/auctions.json
  static/css/style.css
Labels: frontend

#133 Change error message for bids lower than base price.
  server/handlers.go
Labels: backend

#135 release v0.02
  data/data.go
  db/db.go
  media/images/3.png
  media/images/beach.jpeg
  media/images/fridge.jpg
  media/images/test1.jpeg
  media/images/test1.png
  server/handlers.go
  server/routes.go
  server/seed-data/auctions.json
  static/css/style.css
  templates/auction/details.tmpl
  templates/auction_list/card.tmpl
  templates/common/navbar.tmpl
Labels: backend, database, deployment, enhancement, frontend, testing

#134 added tooltip for create auction button
  static/css/style.css
  templates/common/navbar.tmpl
Labels: frontend

#137 Cards styling
  static/css/style.css
Labels: enhancement, frontend

#138 Add tags to the auction detail page
  server/handlers.go
  templates/auction/details.tmpl
Labels: frontend

#140 Create auction styling
  static/css/style.css
  templates/create_auction/form.tmpl
Labels: frontend

#141 Change the display of tags
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: frontend

#142 Create auction styling
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: enhancement, frontend

#143 Fix tag not saving problem in auction create page
  templates/create_auction/index.tmpl
Labels: frontend

#145 Fix 404 and blank page problem
  templates/auction_list/index.tmpl
  templates/common/navbar.tmpl
Labels: frontend

#146 release v0.03
  server/handlers.go
  server/seed-data/auctions.json
  static/css/style.css
  templates/auction/details.tmpl
  templates/auction_list/card.tmpl
  templates/auction_list/index.tmpl
  templates/common/navbar.tmpl
  templates/create_auction/form.tmpl
  templates/create_auction/index.tmpl
Labels: backend, enhancement, frontend, testing

#147 removed navbar dots
  templates/common/navbar.tmpl
Labels: frontend
